name: EverShop
main: com.evermc.evershop.EverShop
version: 1.0
description: EverShop-1.0
author: djytw
load: POSTWORLD
depend:
  - Vault
softdepend:
  - WorldGuard
  - LockettePro
api-version: 1.14

commands:
  evershop:
    description: 'evershop'
    aliases: [es]

permissions:
  evershop.use:
    default: true